/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicioinig.Vista;

import ejercicioinig.java.TextPrompt;
import ejercicioinig.controlador.RConnection;
import java.awt.Color;
import java.awt.FlowLayout;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import java.sql.*;

/**
 *
 * @author Simulacion15
 */
public class Sucursal extends javax.swing.JFrame {

    /**
     * Creates new form Persona
     */
    public Sucursal() {
        initComponents();
        TextPrompt direccion = new TextPrompt("Direccion", direccionSucu);
        TextPrompt nomSucu = new TextPrompt("Nombre de la sucursal", nombreSucu);
        TextPrompt estado = new TextPrompt("Estado", estadoSucu);
        TextPrompt pais = new TextPrompt("Pais", pasiSucu);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        newClass1 = new ejercicioinig.Vista.NewClass();
        direccionSucu = new javax.swing.JTextField();
        nombre123 = new ejercicioinig.Vista.NewClass();
        nombreSucu = new javax.swing.JTextField();
        nombre1 = new ejercicioinig.Vista.NewClass();
        estadoSucu = new javax.swing.JTextField();
        nombre2 = new ejercicioinig.Vista.NewClass();
        pasiSucu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newClass6 = new ejercicioinig.Vista.NewClass();
        enviarSucursal = new javax.swing.JButton();
        newClass7 = new ejercicioinig.Vista.NewClass();
        jButton3 = new javax.swing.JButton();

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Enviar");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 247, 247));

        newClass1.setBackground(new java.awt.Color(255, 255, 255));
        newClass1.setRoundBottomLeft(50);
        newClass1.setRoundBottomRight(50);
        newClass1.setRoundTopLeft(50);
        newClass1.setRoundTopRight(50);

        direccionSucu.setForeground(new java.awt.Color(204, 204, 204));
        direccionSucu.setBorder(null);
        direccionSucu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionSucuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newClass1Layout = new javax.swing.GroupLayout(newClass1);
        newClass1.setLayout(newClass1Layout);
        newClass1Layout.setHorizontalGroup(
            newClass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newClass1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(direccionSucu, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        newClass1Layout.setVerticalGroup(
            newClass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newClass1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(direccionSucu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nombre123.setBackground(new java.awt.Color(255, 255, 255));
        nombre123.setRoundBottomLeft(50);
        nombre123.setRoundBottomRight(50);
        nombre123.setRoundTopLeft(50);
        nombre123.setRoundTopRight(50);

        nombreSucu.setForeground(new java.awt.Color(204, 204, 204));
        nombreSucu.setBorder(null);
        nombreSucu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreSucuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nombre123Layout = new javax.swing.GroupLayout(nombre123);
        nombre123.setLayout(nombre123Layout);
        nombre123Layout.setHorizontalGroup(
            nombre123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nombre123Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(nombreSucu, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nombre123Layout.setVerticalGroup(
            nombre123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nombre123Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreSucu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nombre1.setBackground(new java.awt.Color(255, 255, 255));
        nombre1.setRoundBottomLeft(50);
        nombre1.setRoundBottomRight(50);
        nombre1.setRoundTopLeft(50);
        nombre1.setRoundTopRight(50);

        estadoSucu.setForeground(new java.awt.Color(204, 204, 204));
        estadoSucu.setBorder(null);
        estadoSucu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoSucuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nombre1Layout = new javax.swing.GroupLayout(nombre1);
        nombre1.setLayout(nombre1Layout);
        nombre1Layout.setHorizontalGroup(
            nombre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nombre1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(estadoSucu, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nombre1Layout.setVerticalGroup(
            nombre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nombre1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(estadoSucu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nombre2.setBackground(new java.awt.Color(255, 255, 255));
        nombre2.setRoundBottomLeft(50);
        nombre2.setRoundBottomRight(50);
        nombre2.setRoundTopLeft(50);
        nombre2.setRoundTopRight(50);

        pasiSucu.setForeground(new java.awt.Color(204, 204, 204));
        pasiSucu.setBorder(null);
        pasiSucu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasiSucuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nombre2Layout = new javax.swing.GroupLayout(nombre2);
        nombre2.setLayout(nombre2Layout);
        nombre2Layout.setHorizontalGroup(
            nombre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nombre2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pasiSucu, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nombre2Layout.setVerticalGroup(
            nombre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nombre2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(pasiSucu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Insertar Sucursal");

        newClass6.setBackground(new java.awt.Color(255, 102, 0));
        newClass6.setRoundBottomLeft(50);
        newClass6.setRoundBottomRight(50);
        newClass6.setRoundTopLeft(50);
        newClass6.setRoundTopRight(50);

        enviarSucursal.setBackground(new java.awt.Color(255, 102, 0));
        enviarSucursal.setForeground(new java.awt.Color(255, 255, 255));
        enviarSucursal.setText("Enviar");
        enviarSucursal.setBorderPainted(false);
        enviarSucursal.setContentAreaFilled(false);
        enviarSucursal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarSucursalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newClass6Layout = new javax.swing.GroupLayout(newClass6);
        newClass6.setLayout(newClass6Layout);
        newClass6Layout.setHorizontalGroup(
            newClass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newClass6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enviarSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );
        newClass6Layout.setVerticalGroup(
            newClass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newClass6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enviarSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        newClass7.setBackground(new java.awt.Color(255, 255, 255));
        newClass7.setRoundBottomLeft(50);
        newClass7.setRoundBottomRight(50);
        newClass7.setRoundTopLeft(50);
        newClass7.setRoundTopRight(50);

        jButton3.setForeground(new java.awt.Color(255, 102, 0));
        jButton3.setText("Regresar");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newClass7Layout = new javax.swing.GroupLayout(newClass7);
        newClass7.setLayout(newClass7Layout);
        newClass7Layout.setHorizontalGroup(
            newClass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newClass7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );
        newClass7Layout.setVerticalGroup(
            newClass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newClass7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(newClass6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(newClass7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(493, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(newClass1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombre123, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombre2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(newClass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(nombre123, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newClass6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newClass7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreSucuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreSucuActionPerformed
       /* LineBorder lineBorder =new LineBorder(Color.white, 111, true);
        nombre.setBorder(lineBorder );*/
        UIManager.put("TextComponent.arc",300);
    }//GEN-LAST:event_nombreSucuActionPerformed

    private void direccionSucuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionSucuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionSucuActionPerformed

    private void estadoSucuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoSucuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoSucuActionPerformed

    private void pasiSucuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasiSucuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasiSucuActionPerformed

    private void enviarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarSucursalActionPerformed
        try{
            RConnection cone = new RConnection();
            Connection conexion = cone.conectar();
           
            PreparedStatement insertar = conexion.prepareStatement("insert into sucursal values(?,?,?,?,?)");
            insertar.setString(1,"0");
            insertar.setString(2,direccionSucu.getText());
            insertar.setString(3,nombreSucu.getText());
            insertar.setString(4,estadoSucu.getText());
            insertar.setString(5,pasiSucu.getText());
            
            insertar.executeUpdate();
            JOptionPane.showMessageDialog(null,"Datos Registrados");
            cone.desconectar();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_enviarSucursalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        VistaMenu menu= new VistaMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField direccionSucu;
    private javax.swing.JButton enviarSucursal;
    private javax.swing.JTextField estadoSucu;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private ejercicioinig.Vista.NewClass newClass1;
    private ejercicioinig.Vista.NewClass newClass6;
    private ejercicioinig.Vista.NewClass newClass7;
    private ejercicioinig.Vista.NewClass nombre1;
    private ejercicioinig.Vista.NewClass nombre123;
    private ejercicioinig.Vista.NewClass nombre2;
    private javax.swing.JTextField nombreSucu;
    private javax.swing.JTextField pasiSucu;
    // End of variables declaration//GEN-END:variables
}
