/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicioinig.Vista;

/**
 *
 * @author thero
 */
public class VistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InsertarP = new javax.swing.JButton();
        InsertarG = new javax.swing.JButton();
        MostrarPG = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        ModificarP = new javax.swing.JButton();
        ModificarG = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 247, 247));

        InsertarP.setBackground(new java.awt.Color(255, 102, 0));
        InsertarP.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 12)); // NOI18N
        InsertarP.setForeground(new java.awt.Color(255, 255, 204));
        InsertarP.setText("Insertar Personas");
        InsertarP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));
        InsertarP.setBorderPainted(false);
        InsertarP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InsertarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarPActionPerformed(evt);
            }
        });

        InsertarG.setBackground(new java.awt.Color(255, 102, 0));
        InsertarG.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 12)); // NOI18N
        InsertarG.setForeground(new java.awt.Color(255, 255, 204));
        InsertarG.setText("Insertar Sucursal");
        InsertarG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));
        InsertarG.setBorderPainted(false);
        InsertarG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InsertarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarGActionPerformed(evt);
            }
        });

        MostrarPG.setBackground(new java.awt.Color(255, 102, 0));
        MostrarPG.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 12)); // NOI18N
        MostrarPG.setForeground(new java.awt.Color(255, 255, 204));
        MostrarPG.setText("Mostrar personas y sucursales");
        MostrarPG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));
        MostrarPG.setBorderPainted(false);
        MostrarPG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MostrarPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarPGActionPerformed(evt);
            }
        });

        Eliminar.setBackground(new java.awt.Color(255, 102, 0));
        Eliminar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 12)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 255, 204));
        Eliminar.setText("Eliminar personas y sucursales");
        Eliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));
        Eliminar.setBorderPainted(false);
        Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        ModificarP.setBackground(new java.awt.Color(255, 102, 0));
        ModificarP.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 12)); // NOI18N
        ModificarP.setForeground(new java.awt.Color(255, 255, 204));
        ModificarP.setText("Modificar personas");
        ModificarP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));
        ModificarP.setBorderPainted(false);
        ModificarP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarPActionPerformed(evt);
            }
        });

        ModificarG.setBackground(new java.awt.Color(255, 102, 0));
        ModificarG.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 12)); // NOI18N
        ModificarG.setForeground(new java.awt.Color(255, 255, 204));
        ModificarG.setText("Modificar sucursales");
        ModificarG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));
        ModificarG.setBorderPainted(false);
        ModificarG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarGActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(255, 102, 0));
        jTextField1.setForeground(new java.awt.Color(255, 255, 254));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Menú de Grupo");
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setDisabledTextColor(new java.awt.Color(255, 102, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicioinig/images/pollo-feliz-logo-07B976E9BA-seeklogo.com.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 94, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InsertarP, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InsertarG, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MostrarPG, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModificarG, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModificarP, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(InsertarG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InsertarP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MostrarPG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ModificarG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ModificarP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarPActionPerformed
        Empleado ventana= new Empleado();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InsertarPActionPerformed

    private void InsertarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarGActionPerformed
        Sucursal ventana= new Sucursal();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InsertarGActionPerformed

    private void MostrarPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarPGActionPerformed
        ventanaPrueba ventana= new ventanaPrueba();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MostrarPGActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        ventanaPrueba ventana= new ventanaPrueba();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarPActionPerformed
        ventanaPrueba ventana= new ventanaPrueba();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ModificarPActionPerformed

    private void ModificarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarGActionPerformed
        ventanaPrueba ventana= new ventanaPrueba();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ModificarGActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton InsertarG;
    private javax.swing.JButton InsertarP;
    private javax.swing.JButton ModificarG;
    private javax.swing.JButton ModificarP;
    private javax.swing.JButton MostrarPG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
